name       : getdns
version    : 1.4.2
release    : 1
source     :
    - https://www.getdnsapi.net/dist/getdns-1.4.2.tar.gz : 1685b82dfe297cffc4bae08a773cdc88a3edf9a4e5a1ea27d8764bb5affc0e80
license    : BSD-3-Clause
component  : network.util
summary    : A modern asynchronous DNS API
description: |
    getdns is a modern asynchronous DNS API. It implements DNS entry points from a design developed and vetted by application developers, in an API specification. The open source C implementation of getdns is developed and maintained in collaboration by NLnet Labs, Sinodun and No Mountain Software.
builddeps  :
    # pkgconfig(check)
    - pkgconfig(libbsd-overlay)
    - pkgconfig(libidn2)
    - pkgconfig(libunbound)
    - pkgconfig(libuv)
setup      : |
    %patch -p1 < $pkgfiles/0001-Cleanup-Makefile.patch

    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
# tests require a network connection -> disabled per default
#networking : yes
#check      : |
#    %make test
