name       : getdns
version    : 1.6.0
release    : 10
source     :
    - https://github.com/getdnsapi/getdns/releases/download/v1.6.0/getdns-1.6.0.tar.gz : 40e5737471a3902ba8304b0fd63aa7c95802f66ebbc6eae53c487c8e8a380f4a
license    : BSD-3-Clause
component  : network.util
summary    : A modern asynchronous DNS API
description: |
    getdns is a modern asynchronous DNS API. It implements DNS entry points from a design developed and vetted by application developers, in an API specification. The open source C implementation of getdns is developed and maintained in collaboration by NLnet Labs, Sinodun and No Mountain Software.
builddeps  :
    - pkgconfig(check)
    - pkgconfig(libbsd-overlay)
    - pkgconfig(libidn2)
    - pkgconfig(libunbound)
    - pkgconfig(libuv)
    - libev-devel
setup      : |
    %cmake -DENABLE_STATIC=OFF
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/doc
